server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ead-course
    username: postgres
    password: admin
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      show-sql: true
      hibernate:
        jdbc:
          non-contextual-creation: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
